apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cars.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: Car
    plural: cars
    singular: car
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                make:
                  type: string
                model:
                  type: string
            status:
              type: object
              properties:
                wheelNames:
                  type: array
                  items:
                    type: string
          x-kubernetes-preserve-unknown-fields: true
